[package]
name = "media_server"
version = "0.1.0"
authors = ["ME_Kun_Han <hanvskun@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
